modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "yep"
version = "${version}"
displayName = "Yep"
logoFile = "icon.png"
authors = "foooooooooooo, unilock"
description = '''
Forwards death messages and similar events to Velocity proxy plugins
'''

[[dependencies.yep]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.yep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "SERVER"
